### ISSUE TITLE
PDE_reader_i() - file "is most likely secured and cannot be processed!"

### ISSUE THREAD

**Issue by lnordgreen** [erikstricker/PDE#1]
Hello,

This seems like a really interesting package. Everything seemed to install ok, and I checked with `PDE_check_Xpdf_install()` 
But I tried it out on some PDFs, and they all returned the same error: 

'filename' "is most likely secured and cannot be processed!"

Do you know what this means, or what it could be caused by?

Many thanks!

**Comment by erikstricker** [comment]
Thank you for your interest in the PDE package! The error sound like there is an issue with xpdf creating the html or txt files. I am currently trying to upload the latest version (1.4.2) to github which includes potential bug fixes for this error. 

In the meantime, you could install the latest version of the package directly from CRAN: [https://cran.r-project.org/package=PDE](url)

Also, if the error persists with the updated version, would you be able to share a pdf that does not work (see email address on CRAN)?

Best
Erik

**Comment by erikstricker** [comment]
Lastest version is uploaded on github as well. Please let me know if your problem persists.

**Comment by lnordgreen** [comment]
Thank you for the answer and for the update. 

I re-installed PDE from GitHub just now, and then tried to run PDE_analyzer_i().

However, it now says that `pdftotext, pdftohtml and pdftopng files not detected. Please install the Xpdf command line tools again using PDE_install_Xpdftools4.02()`

So I tried running `PDE_install_Xpdftools4.02()` again, but it gave me the following error message:

```
trying URL 'https://raw.githubusercontent.com/erikstricker/PDE/master/inst/examples/bin/xpdf-tools-win-4.02.zip'
Error in utils::download.file("https://raw.githubusercontent.com/erikstricker/PDE/master/inst/examples/bin/xpdf-tools-win-4.02.zip",  : 
  cannot open URL 'https://raw.githubusercontent.com/erikstricker/PDE/master/inst/examples/bin/xpdf-tools-win-4.02.zip'
In addition: Warning message:
In utils::download.file("https://raw.githubusercontent.com/erikstricker/PDE/master/inst/examples/bin/xpdf-tools-win-4.02.zip",  :
  cannot open URL 'https://raw.githubusercontent.com/erikstricker/PDE/master/inst/examples/bin/xpdf-tools-win-4.02.zip': HTTP status was '404 Not Found'
```

**Comment by erikstricker** [comment]
In the last update, I accidentally deleted the bin folders. I apologize for that! Please try again.
