### ISSUE TITLE
Error installing PDE on Spanish version of Windows

### ISSUE THREAD

**Issue by evgc01** [erikstricker/PDE#2]
Hi,

I tried to install PDE on R for windows (spanish version) but when I ran the command "PDE_install_Xpdftools4.02()" I got the following strange error:

Error in system(paste0("\"", pdftotext_location[i], "\" \"", "-layout",  : 
  '"INFORMACI�N: no se pudo encontrar ning�n archivo para los patrones dados."' not found

INFORMACIÓN: no se pudo encontrar ningún archivo para los patrones dados"

Browsing across the source code of "PDE_install_Xpdftools4.02()", I found it first calls "PDE_check_Xpdf_install()".

And in turn PDE_check_Xpdf_install() executes this line of code several times:

        if (sysname == "Windows") {
            pdftotext_location <- suppressWarnings(system("C:\\WINDOWS\\system32\\cmd.exe /c where pdftotext", 
                intern = TRUE))
            if ("INFO: Could not find files for the given pattern(s)." %in% 
                pdftotext_location)

"INFO: Could not find files for the given pattern(s)" is the response "where" command returns when a file is not found but just in  the english version of windows. 
In the spanish one the response is "INFORMACIÓN: no se pudo encontrar ningún archivo para los patrones dados" which is the spanish translation, and because of encodings, the non english charactes appears distorted. It happens the system is windows, but obviouly is not a valid location, so an error is thrown.

Is there any workaround?

Best regards.

**Comment by erikstricker** [comment]
Hi,
Thank you for letting me know about the issue. I will post an updated version on github and CRAN by tomorrow evening. In the meantime, if you installed the github version of the package you use the following fix:
1) Locate the PDE package location with:
`system.file(package = "PDE")`
2) Open the `bin` subdirectory and create a file called `XPDF_DIR.config` with a text editor in the subdirectory.
3) Enter 3 lines into the file with a text editor:
`<PDE_package_dir>\bin\xpdf-tools-win-4.02\bin64\pdftotext.exe
<PDE_package_dir>\bin\xpdf-tools-win-4.02\bin64\pdftohtml.exe
<PDE_package_dir>\bin\xpdf-tools-win-4.02\bin64\pdftopng.exe`
replacing `<PDE_package_dir>` with the filepath from the `system.file(package = "PDE")` command.

That should fix the problem and get rid of the requirement to run `PDE_install_Xpdftools4.02()`.

Best
Erik

**Comment by erikstricker** [comment]
I just submitted the updated script to github. Version 1.4.4 with be up with fix on CRAN on August 7.
