### ISSUE TITLE
Different UI as per Mac documentation

### ISSUE THREAD

**Issue by fontikar** [erikstricker/PDE#4]
Hi @erikstricker very cool idea for an R package!
I can see that the package is still in dev but just wanted to let you know that the mac interface is different to that of your screenshots! 

This made it hard me to try to set up the program to start extracting data!
See attached

<img width="746" alt="Screenshot 2024-02-25 at 10 59 18 am" src="https://github.com/erikstricker/PDE/assets/12161802/3f7d117d-ddf1-4fd5-9068-b4957e397f21">

I'm using PDE_1.4.8

Any advice or useful documentation pls send them my way!

**Comment by erikstricker** [comment]
Dear Fonti,
This interface seems to be correct but for the PDE_reader. In order to analyze PDF files you want to open the PDE_analyzer_i(). Please let me know if this will pull up the correct interface.
Best,
Erik
